heat_template_version: 2013-05-23
parameters:
####################################     BOOT VM PARAMETERS
  image:
    type: string
    default: TestVM
  flavor:
    type: string
    default: m1.tiny
  key_pair:
    type: string
    default: heat_key
####################################     ZABBIX AUTH PARAMETERS
  zb_server:
    type: string
    default: 172.16.40.254
  zb_user:
    type: string
    default: admin
  zb_pass:
    type: string
    default: zabbix
####################################     VYATTA AUTH PARAMETERS
  vy_server:
    type: string
    default: 172.16.40.177
  vy_user:
    type: string
    default: vyatta
  vy_pass:
    type: string
    default: vyatta
####################################     CONFIGURE NETWORK FOR ZABBIX MONITORING
  public_net:
    type: string
    default: c01e5d9e-08f0-4dbe-8ed6-3566388e46b5
  private_net:
    type: string
    default: c64651ad-c492-43f4-b2a9-daebc0b901ec
####################################     VYATTA FIREWALL PARAMETERS
  name:
    type: string
    default: Heat_Demo
  rule_id:
    type: string
    default: '10'
  port:
    type: string
    default: '80'

resources:

####################################     DEFAULT RESOURCES
  server:
    type: OS::Nova::Server
    properties:
      name: heat_server
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
        - port: { get_resource: server_port }

  server_port:
    type: OS::Neutron::Port
    properties:
      network_id: {get_param: private_net}
  fip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: {get_param: public_net}
      port_id: { get_resource: server_port }
####################################     CUSTOM RESOURCES
  monitor:
    type: OS::Zabbix::Ping
    properties:
      zabbix_server: {get_param: zb_server}
      user: {get_param: zb_user}
      password: {get_param: zb_pass}
      server_ip: {get_attr: [fip, floating_ip_address]}

  firewall:
    type: OS::Vyatta::Firewall
    properties:
      v_server: {get_param: vy_server}
      user: {get_param: vy_user}
      password: {get_param: vy_pass}
      name: {get_param: name}
      rule_id: {get_param: rule_id}
      port: {get_param: port} 
      ip: {get_attr: [fip, floating_ip_address]}
