heat_template_version: 2013-05-23
parameters:
  image:
    type: string
    default: TestVM
  flavor:
    type: string
    default: m1.tiny
  key_pair:
    type: string
    default: heat_key

  zb_server:
    type: string
    default: 172.16.40.254
  zb_user:
    type: string
    default: admin
  zb_pass:
    type: string
    default: zabbix

  public_net:
    type: string
    default: c01e5d9e-08f0-4dbe-8ed6-3566388e46b5
  private_net:
    type: string
    default: c64651ad-c492-43f4-b2a9-daebc0b901ec

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: {get_param: image}
      flavor: {get_param: flavor}
      networks:
        - port: { get_resource: port }

  port:                                                                      
    type: OS::Neutron::Port                                                     
    properties:                                                                 
      network_id: {get_param: private_net}                                      
  fip:                                                               
    type: OS::Neutron::FloatingIP                                               
    properties:                                                                 
      floating_network_id: {get_param: public_net}                                 
      port_id: { get_resource: port }  
  
  monitor:
    type: OS::Zabbix::Ping
    properties:
      zabbix_server: {get_param: zb_server}
      user: {get_param: zb_user}
      password: {get_param: zb_pass}
      server_ip: {get_attr: [fip, floating_ip_address]}
      
outputs:
  val1:
    description: ddddd
    value: {get_attr: [fip, floating_ip_address]}

        #  firewall:
        #    type: OS::Vyatta::Firewall
        #    properties:
     

